// <auto-generated />
namespace ProductionCompanyHelper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class db_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202406250926318_db_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
